### ISSUE TITLE
Support for authenticating with API keys

### ISSUE THREAD

**Issue by mwild1** [pesvut/sgx-twilio#11]
Thanks for working on this!

Currently the SGX depends on authenticating to Twilio using the account's SID and access token. This grants full access to the Twilio account, and cannot be revoked.

Support for authenticating using API keys would be a nice security improvement.

More information on the different types of [Twilio credentials](https://www.twilio.com/docs/usage/requests-to-twilio#credentials).

**Comment by nickypro** [comment]
Added support for Api Tokens for both IQ ( d4af1a292f4af42391fdb5725f260f74c2de4a21 )  and bot ( 820784a8caf551b57032797b7c302b66aa9b3fe6 ) registration. 

By default, bot registration will ask for an API key, but there is the option to provide auth token instead.

If an Auth Token IS provided, then that will be preferred to the API key for authentication.
