### ISSUE TITLE
Getting two replies on successful registration

### ISSUE THREAD

**Issue by singpolyma** [pesvut/sgx-twilio#7]
Even after #6 I still on a successful registration (and I see the keys have been set properly in redis) get two replies from the component, which confuses Gajim:

```
<iq xmlns="jabber:client" type="error" from="component2.localhost" id="9d23adb5-a3bd-4914-86ec-c7633d1e59bb" to="test@localhost/gajim">
<query xmlns="jabber:iq:register">
<username>[REDACTED]</username>
<password>[REDACTED]</password>
<number>[REDACTED]</number>
</query>
<error type="cancel">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
</error>
</iq>

<iq xmlns="jabber:client" type="result" from="component2.localhost" id="9d23adb5-a3bd-4914-86ec-c7633d1e59bb" to="test@localhost/gajim" />
```

**Comment by nickypro** [comment]
After some testing seems like an internal thing with xmpp.js that needs to be configured, looking into that now

**Comment by nickypro** [comment]
Looks like there is a specific way in which iq needs to be handled: 
https://github.com/xmppjs/xmpp.js/tree/master/packages/iq#callee
Going to implement the different way now

**Comment by nickypro** [comment]
Fixed in commit: https://github.com/pesvut/sgx-twilio/commit/057f9fd7441dd204df9ee4cad2c52338cf83b27f
